# Enable vi mode
# bindkey -v

sshL() { ssh -L 6000:"$1":22 cam45819@ushpc-login2.gsk.com; }
sshQ() { ssh -O exit ushpc-login2.gsk.com; lsof -ti:6000 | xargs kill -9 }
sshQ() { ssh -O exit ushpc-login2.gsk.com; lsof -ti:8083 | xargs kill -9 }
kill_port() { lsof -ti:"$1" | xargs kill -9 }
upload() { rsync -rlptzv --progress --delete --exclude=.git --filter=":- .gitignore" . "cam45819@ushpc-login1.gsk.com":/home/cam45819/repos/${PWD##*/} }
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# rsync example
# rsync -chavzP --stats /path/to/local/storage cam45819@ushpc-login1.gsk.com:/path/to/destination
# scrape site for offline docs https://superuser.com/a/42428
# wget -m -p -E -k -np www.example.com/documentation/

file_upload() { scp -r "$1" cam45819@ushpc-login2.gsk.com:"$2"; }

download() { scp cam45819@ushpc-login2.gsk.com:"$1" .; }
azure() { echo "az login"; echo "az acr login -n gskaiml"; }
nb2script() { jupyter nbconvert --to script --no-prompt "$1"; }
alias sq="docker ps"
alias rcp="rsync -ah --info=progress2"
alias black_fix="rm -rf ~/Library/Caches/black"
alias ner="source activate aiml-ner"
alias kga="source activate aiml_kga_network_all"
alias tools="source activate tools-aiml-nlp-webapp-backend"
alias awscli='aws --endpoint=https://objstr.gsk.com:9021'
alias rsync2='rsync -chavzP --stats'
alias sa="source activate"
alias sd="source deactivate"
alias lg='lazygit'
alias lzd='lazydocker'
alias chrome="open -a 'Google Chrome'"
alias nano="echo 'Instead use: hx'"
alias kerb="kinit -k -t $HOME/$USER.keytab $USER"
alias gauth="gcloud auth application-default login"
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias conda='micromamba'

# export UV_EXTRA_INDEX_URL=$(grep 'extra-index-url' ~/.config/pip/pip.conf | cut -d '=' -f 2-) # not good, uses index for everything
export VISUAL=hx
export EDITOR=hx
export MAMBA_NO_BANNER=1
export MAMBA_ROOT_PREFIX='/Users/cam45819/micromamba'
export HTTP_PROXY='http://nodecrypt.gtm.corpnet2.com:800'
export HTTPS_PROXY='http://nodecrypt.gtm.corpnet2.com:800'
export NO_PROXY="*.gsk.com,*.corpnet1.com,*.corpnet2.com,10.0.0.0/8,localhost"
export SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
export REQUESTS_CA_BUNDLE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
export CARGO_HTTP_CAINFO=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
export GRPC_DEFAULT_SSL_ROOTS_FILE_PATH=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
export ORACLE_HOME=$HOME/instantclient_19_8
export TNS_ADMIN=$ORACLE_HOME/network/admin
export PATH=$PATH:$ORACLE_HOME
# export PATH=$PATH:$(brew --prefix)/opt/llvm/bin
export LD_LIBRARY_PATH=~/lib:$ORACLE_HOME
# export R_HOME=/Users/cam45819/models/kazu_model_pack_public-v1.4.0
export KAZU_MODEL_PACK=/Users/cam45819/models/kazu_model_pack_public-v1.4.0
export PIP_LOG=/tmp/pip_log.txt
export KMP_DUPLICATE_LIB_OK=True
export kerb="kinit -k -t $HOME/$USER.keytab $USER"
export PARQUET_DIR="/Users/cam45819/repos/aiml-jules-os-mvp/agent-data/denormalised_files"
export ID_RSA_PUB=~/.ssh/id_ed25519.pub
export DOCKER_HOST="unix://$HOME/.colima/default/docker.sock"
export BIGQUERYRC="~/.config/gcloud/.bigqueryrc"
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew/Library/.homebrew-is-managed-by-nix";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export PATH="/opt/homebrew/anaconda3/bin":$PATH;
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1

autoload -U colors && colors
PS1="%{$fg[green]%}[local]%{$reset_color%}:%{$fg[blue]%}%1d%{$reset_color%}$ "
ulimit -S -n 40000
export PATH=$HOME/bin:/Users/cam45819/miniconda/bin:/usr/local/bin:/sbin:/usr/sbin:$PATH


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/Users/cam45819/miniconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "/Users/cam45819/miniconda/etc/profile.d/conda.sh" ]; then
#        . "/Users/cam45819/miniconda/etc/profile.d/conda.sh"
#     else
#         export PATH="/Users/cam45819/miniconda/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# <<< conda initialize <<<


autoload -U +X bashcompinit && bashcompinit
autoload -Uz compinit && compinit
complete -o nospace -C /usr/local/bin/terraform terraform

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Created by `pipx` on 2023-11-10 10:33:55
export PATH="$PATH:/Users/cam45819/.local/bin"

# pyenv stuff?
export PATH="/Users/username/.pyenv:$PATH"
# eval "$(pyenv init -)"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

n ()
{
    # Block nesting of nnn in subshells
    [ "${NNNLVL:-0}" -eq 0 ] || {
        echo "nnn is already running"
        return
    }

    # The behaviour is set to cd on quit (nnn checks if NNN_TMPFILE is set)
    # If NNN_TMPFILE is set to a custom path, it must be exported for nnn to
    # see. To cd on quit only on ^G, remove the "export" and make sure not to
    # use a custom path, i.e. set NNN_TMPFILE *exactly* as follows:
    #      NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    # The command builtin allows one to alias nnn to n, if desired, without
    # making an infinitely recursive alias
    command nnn -e "$@"

    [ ! -f "$NNN_TMPFILE" ] || {
        . "$NNN_TMPFILE"
        rm -f "$NNN_TMPFILE" > /dev/null
    }
}
export NNN_FIFO=/tmp/nnn.fifo
export NNN_PLUG='p:preview-tui'

start_colima() {
  local CERTS="${HOME}/.ca-certificates"
  local URL="us-central1-docker.pkg.dev"
  mkdir -p ${CERTS}
  openssl s_client -showcerts -connect ${URL} </dev/null 2>/dev/null|openssl x509 -outform PEM >${CERTS}/docker-com.pem
  openssl s_client -showcerts -verify 5 -connect ${URL} </dev/null 2>/dev/null | sed -ne '/-BEGIN/,/-END/p' >${CERTS}/docker-com-chain.pem
  colima start
  
  colima ssh -- sudo cp ${CERTS}/* /usr/local/share/ca-certificates/
  colima ssh -- sudo update-ca-certificates
  colima ssh -- sudo service docker restart
}

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE='/Users/cam45819/.nix-profile/bin/micromamba';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell zsh --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias micromamba="$MAMBA_EXE"  # Fallback on help from mamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<

eval "$(direnv hook zsh)"
