#!/usr/bin/env python3
# This entire thing is unnecessary post v3.13.0a3
# https://github.com/python/cpython/issues/73965

def is_vanilla() -> bool:
    """ :return: whether running "vanilla" Python <3.13 """
    import sys
    return not hasattr(__builtins__, '__IPYTHON__') and 'bpython' not in sys.argv[0] and sys.version_info < (3, 13)


def setup_history():
    """ read and write history from state file """
    import os
    import atexit
    import readline
    from pathlib import Path

    history_path_str = os.environ.get('PYTHON_HISTORY')
    state_home_str = os.environ.get('XDG_STATE_HOME')

    if history_path_str:
        history = Path(history_path_str)
    elif state_home_str:
        history = Path(state_home_str) / 'python_history'
    else:
        history = Path.home() / '.local' / 'state' / 'python_history'

    # https://github.com/python/cpython/issues/105694
    if not history.is_file():
        # If this breaks, manually copy ~/.python_history to ~/.local/state/python_history
        readline.write_history_file(str(history)) # breaks on macos + python3 without this.

    readline.read_history_file(str(history))
    atexit.register(readline.write_history_file, str(history))


if is_vanilla():
    setup_history()